### ISSUE TITLE
issues with sending Push notification to APN

### ISSUE THREAD

**Issue by ojczeo** [activitree/meteor-push#17]
When I'm trying to send notifications using `Push.send` getting this error:
```
I20191106-12:11:13.331(1)?   errorInfo:
I20191106-12:11:13.332(1)?    { code: 'messaging/invalid-payload',
I20191106-12:11:13.332(1)?      message: 'android.data must only contain string values' },
I20191106-12:11:13.332(1)?   codePrefix: 'messaging' }
I20191106-12:11:13.332(1)? Push: Could not send notification id: "xxx", Error: android.data must only contain string values
```

**Comment by paulincai** [comment]
I think the error message is pretty clear. Anything I can help you with? If your debugging is set to true, I think you should see the final notification before it sends out. Your Android data object should only have key of data type string. This is the requirement of Firebase.

You have multiple data objects there (data - global, androidData, iosData). Android data.keys should be string. For IOS or Web they can be anything.

**Comment by ojczeo** [comment]
@paulincai the problem is I'm not sending any androidData, notifications object looks like that:
```
{
 title: `Someone liked your product. `,
        body: `Product name.`,
        badge: 1,
        userId: "4DgfWwrBgAFXTuGfc"
}
```

**Comment by ojczeo** [comment]
@paulincai 
```
Final notification right before shoot out: {
I20191106-12:50:16.440(1)?       "android": {
I20191106-12:50:16.441(1)?             "data": {
I20191106-12:50:16.441(1)?                   "title": "Someone liked your post. ",
I20191106-12:50:16.441(1)?                   "body": "testlikes your post test.",
I20191106-12:50:16.441(1)?                   "tag": "undefined",
I20191106-12:50:16.441(1)?                   "channel_id": "com.shopvine.shopvine"
I20191106-12:50:16.441(1)?             },
I20191106-12:50:16.441(1)?             "fcm_options": {
I20191106-12:50:16.441(1)?                   "analytics_label": "activitreeSomething"
I20191106-12:50:16.441(1)?             }
I20191106-12:50:16.441(1)?       },
I20191106-12:50:16.441(1)?       "apns": {
I20191106-12:50:16.441(1)?             "headers": {
I20191106-12:50:16.441(1)?                   "apns-priority": "10"
I20191106-12:50:16.441(1)?             },
I20191106-12:50:16.441(1)?             "payload": {
I20191106-12:50:16.442(1)?                   "aps": {
I20191106-12:50:16.442(1)?                         "alert": {
I20191106-12:50:16.442(1)?                               "title": "Someone liked your post. ",
I20191106-12:50:16.442(1)?                               "body": "testlikes your post test."
I20191106-12:50:16.442(1)?                         },
I20191106-12:50:16.442(1)?                         "badge": 1,
I20191106-12:50:16.442(1)?                         "sound": "",
I20191106-12:50:16.442(1)?                         "data": {}
I20191106-12:50:16.442(1)?                   }
I20191106-12:50:16.442(1)?             },
I20191106-12:50:16.442(1)?             "fcm_options": {
I20191106-12:50:16.442(1)?                   "analytics_label": "activitreeSomething"
I20191106-12:50:16.442(1)?             }
I20191106-12:50:16.442(1)?       },
I20191106-12:50:16.442(1)?       "webpush": {
I20191106-12:50:16.443(1)?             "headers": {
I20191106-12:50:16.443(1)?                   "Urgency": "high"
I20191106-12:50:16.443(1)?             },
I20191106-12:50:16.443(1)?             "data": {},
I20191106-12:50:16.443(1)?             "notification": {
I20191106-12:50:16.443(1)?                   "title": "Someone liked your post. ",
I20191106-12:50:16.443(1)?                   "body": "testlikes your post test."
I20191106-12:50:16.443(1)?             },
I20191106-12:50:16.443(1)?             "fcm_options": {
I20191106-12:50:16.443(1)?                   "link": "https://some_photo_url_or_link_to_something"
I20191106-12:50:16.443(1)?             }
I20191106-12:50:16.443(1)?       },
I20191106-12:50:16.443(1)?       "token": "e05uraMIArA:APA91bEoWoNQBDIHar6tHIDF-G_Gh5uSv-jm8jL_2D51WGFDioCtx4ArvfrW4pn3aeg2Ceupy5OFbVqsRoZ9axV6NtzgNTAQPbcBqNBAuQZmegOjPPmSScvOgcwO4drEEkoKFdQ7VGuE"
I20191106-12:50:16.443(1)? }
```

**Comment by ojczeo** [comment]
```
Final notification right before shoot out: {
I20191106-12:50:16.440(1)?       "android": {
I20191106-12:50:16.441(1)?             "data": {
I20191106-12:50:16.441(1)?                   "title": "Someone liked your post. ",
I20191106-12:50:16.441(1)?                   "body": "testlikes your post test.",
I20191106-12:50:16.441(1)?                   "tag": "undefined",
I20191106-12:50:16.441(1)?                   "channel_id": "com.shopvine.shopvine"
I20191106-12:50:16.441(1)?             },
I20191106-12:50:16.441(1)?             "fcm_options": {
I20191106-12:50:16.441(1)?                   "analytics_label": "activitreeSomething"
I20191106-12:50:16.441(1)?             }
I20191106-12:50:16.441(1)?       },
I20191106-12:50:16.441(1)?       "apns": {
I20191106-12:50:16.441(1)?             "headers": {
I20191106-12:50:16.441(1)?                   "apns-priority": "10"
I20191106-12:50:16.441(1)?             },
I20191106-12:50:16.441(1)?             "payload": {
I20191106-12:50:16.442(1)?                   "aps": {
I20191106-12:50:16.442(1)?                         "alert": {
I20191106-12:50:16.442(1)?                               "title": "Someone liked your post. ",
I20191106-12:50:16.442(1)?                               "body": "testlikes your post test."
I20191106-12:50:16.442(1)?                         },
I20191106-12:50:16.442(1)?                         "badge": 1,
I20191106-12:50:16.442(1)?                         "sound": "",
I20191106-12:50:16.442(1)?                         "data": {}
I20191106-12:50:16.442(1)?                   }
I20191106-12:50:16.442(1)?             },
I20191106-12:50:16.442(1)?             "fcm_options": {
I20191106-12:50:16.442(1)?                   "analytics_label": "activitreeSomething"
I20191106-12:50:16.442(1)?             }
I20191106-12:50:16.442(1)?       },
I20191106-12:50:16.442(1)?       "webpush": {
I20191106-12:50:16.443(1)?             "headers": {
I20191106-12:50:16.443(1)?                   "Urgency": "high"
I20191106-12:50:16.443(1)?             },
I20191106-12:50:16.443(1)?             "data": {},
I20191106-12:50:16.443(1)?             "notification": {
I20191106-12:50:16.443(1)?                   "title": "Someone liked your post. ",
I20191106-12:50:16.443(1)?                   "body": "testlikes your post test."
I20191106-12:50:16.443(1)?             },
I20191106-12:50:16.443(1)?             "fcm_options": {
I20191106-12:50:16.443(1)?                   "link": "https://some_photo_url_or_link_to_something"
I20191106-12:50:16.443(1)?             }
I20191106-12:50:16.443(1)?       },

```

**Comment by ojczeo** [comment]
@paulincai maybe it's related to place below? it's trying to send Anroid message event when it's not defined:
https://github.com/activitree/meteor-push/blob/5cd4677cf566b35cc1ed7b7d516274b0d27f335e/lib/server/pushToDevice.js#L122-L144

**Comment by paulincai** [comment]
Ok... you can read here: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads. Your Android notification will always go as 'data'. You can overwrite keys using the androidData object. So in your case above, I see 'tag' is undefined. I believe that is your problem.

**Comment by ojczeo** [comment]
i don't event want to use android - only APN. I didnt define any tag in
Android data.

śr., 6 lis 2019, 13:27 użytkownik Paul Ailincai <notifications@github.com>
napisał:

**Comment by paulincai** [comment]
In your sending method, could you please add this key: ```notId: Math.round(new Date().getTime() / 1000)```. This will add a unique value to your notification for Android. I understand you don't use Android but in Firebase as you probably notices there is one notification going out for all so we need to satisfy all conditions. Let me know please if this resolves your problem

**Comment by ojczeo** [comment]
@paulincai I've forked your code, and disabled part of your code related to Android.
```js
const note = {
    // android: {
    //   // ttl: '86400s', // use default max of 4 weeks
    //   // collapse_key: string,
    //   priority: defaults.priority,
    //   // restricted_package_name: string,
    //   data: {
    //     title: mongoNote.title,
    //     body: mongoNote.body,
    //     icon: mongoNote.icon || defaults.icon,
    //     color: mongoNote.color || defaults.color,
    //     sound: mongoNote.sound || defaults.sound,
    //     tag: `${mongoNote.notId}`,
    //     // click_action: mongoNote.action
    //     channel_id: mongoNote.channelId || defaults.channelId || defaults.topic,
    //     notification_priority: mongoNote.notificationPriority || defaults.notificationPriority,
    //     visibility: mongoNote.visibility || defaults.visibility,
    //     // notification_count: mongoNote.badge || defaults.badge, // this is supposed to be a number, can't send it because I need it to be a string.
    //     image: mongoNote.imageUrl || defaults.imageUrl,
    //     ...globalData,
    //     ...noteAndroidData
    //   },
    //   fcm_options: {
    //     analytics_label: mongoNote.analyticsLabel || defaults.analyticsLabel
    //   }
    // },
```

**Comment by ojczeo** [comment]
Check out assigning values:
https://github.com/activitree/meteor-push/blob/5cd4677cf566b35cc1ed7b7d516274b0d27f335e/lib/server/notification.js#L14-L35

**Comment by paulincai** [comment]
Ok, I tried to understand what might be the problem here. I think the package is ok, no issues there. I tried to implement as much as possible of the Firebase-Admin configurations and notification keys. It is true, you can't really opt out from one or another but I think you shouldn't. I guess most of the users would aim for all 3: IOS, Android and Web. Or perhaps there are people interested particularly in all mobiles or only the web/PWA.
The ```startup/server/push.js``` file in the example provides defaults which are meant to satisfy all required values. You may have a look here: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification.

It seems that when an icon, or color, or sound etc are not specified, that error is presented. I'd suggest for you to start from the defaults I provided and fine tune for your needs, particularly for your IOS and leave Android untouched. It should then work ok. I am not able to find what are the mandatory key for Android. Anyway I manually removed them from defaults and observed where things start to fail. Thanks for your input on this. This was some necessary learning.

**Comment by Roshdy** [comment]
I wonder how you solved this!

I'm trying to send web-push, i followed everything to the letter!
I even tested from FCM itself and i received the notification.

But i'm still facing the android.data issue on Meteor side:

Here are the logs

```
Final notification right before shoot out: {
I20200515-00:22:30.206(3)?       "android": {
I20200515-00:22:30.207(3)?             "priority": "HIGH",
I20200515-00:22:30.207(3)?             "data": {
I20200515-00:22:30.207(3)?                   "title": "Thank you for enabling Push Notifications",
I20200515-00:22:30.207(3)?                   "body": "You just gained your first 5 stars! 🌟",
I20200515-00:22:30.207(3)?                   "icon": "statusbaricon",
I20200515-00:22:30.207(3)?                   "color": "#337FAE",
I20200515-00:22:30.207(3)?                   "sound": "note",
I20200515-00:22:30.207(3)?                   "tag": "undefined",
I20200515-00:22:30.207(3)?                   "notification_priority": "PRIORITY_DEFAULT",
I20200515-00:22:30.207(3)?                   "visibility": "PRIVATE",
I20200515-00:22:30.207(3)?                   "image": ""
I20200515-00:22:30.207(3)?             },
I20200515-00:22:30.208(3)?             "fcm_options": {
I20200515-00:22:30.208(3)?                   "analytics_label": "default_push"
I20200515-00:22:30.217(3)?             }
I20200515-00:22:30.217(3)?       },
I20200515-00:22:30.217(3)?       "apns": {
I20200515-00:22:30.217(3)?             "headers": {},
I20200515-00:22:30.217(3)?             "payload": {
I20200515-00:22:30.218(3)?                   "aps": {
I20200515-00:22:30.218(3)?                         "alert": {
I20200515-00:22:30.218(3)?                               "title": "Thank you for enabling Push Notifications",
I20200515-00:22:30.218(3)?                               "body": "You just gained your first 5 stars! 🌟"
I20200515-00:22:30.218(3)?                         },
I20200515-00:22:30.218(3)?                         "badge": 1,
I20200515-00:22:30.218(3)?                         "sound": "note.caf",
I20200515-00:22:30.218(3)?                         "data": {}
I20200515-00:22:30.218(3)?                   }
I20200515-00:22:30.218(3)?             },
I20200515-00:22:30.218(3)?             "fcm_options": {
I20200515-00:22:30.218(3)?                   "analytics_label": "default_push",
I20200515-00:22:30.218(3)?                   "image": ""
I20200515-00:22:30.218(3)?             }
I20200515-00:22:30.219(3)?       },
I20200515-00:22:30.219(3)?       "webpush": {
I20200515-00:22:30.219(3)?             "headers": {
I20200515-00:22:30.219(3)?                   "Urgency": "high",
I20200515-00:22:30.219(3)?                   "TTL": "3600000"
I20200515-00:22:30.219(3)?             },
I20200515-00:22:30.219(3)?             "data": {},
I20200515-00:22:30.219(3)?             "notification": {
I20200515-00:22:30.219(3)?                   "title": "Thank you for enabling Push Notifications",
I20200515-00:22:30.219(3)?                   "body": "You just gained your first 5 stars! 🌟",
I20200515-00:22:30.219(3)?                   "icon": "",
I20200515-00:22:30.219(3)?                   "image": ""
I20200515-00:22:30.219(3)?             },
I20200515-00:22:30.219(3)?             "fcm_options": {
I20200515-00:22:30.220(3)?                   "link": "https://m2m-web.herokuapp.com"
I20200515-00:22:30.220(3)?             }
I20200515-00:22:30.220(3)?       },
I20200515-00:22:30.221(3)?       "token": "eaLw_Q6A4uM7Xdd7dlD5G0:APA91bGCJyA3z5ijR4LE3cl01fxA9aCuA_KhsPeGvOtwokQOG6vdUkyji4pqWgUQDMMtBneMs6Pv4xIoVpqZ3dH2HzZmIEDAKqSsdyC9EYQeQbw9flG-IYt-C9OlZ9XRcLj0o5JM_FLE"
I20200515-00:22:30.221(3)? }
```

The rest:

```
Show Full error FirebaseMessagingError: android.data must only contain string values
I20200515-00:22:30.221(3)?     at FirebaseMessagingError.FirebaseError [as constructor] (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/utils/error.js:42:28)
I20200515-00:22:30.227(3)?     at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/utils/error.js:88:28)
I20200515-00:22:30.227(3)?     at new FirebaseMessagingError (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/utils/error.js:254:16)
I20200515-00:22:30.227(3)?     at /Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/messaging/messaging-types.js:71:19
I20200515-00:22:30.229(3)?     at Array.forEach (<anonymous>)
I20200515-00:22:30.229(3)?     at validateStringMap (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/messaging/messaging-types.js:69:22)
I20200515-00:22:30.229(3)?     at validateAndroidConfig (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/messaging/messaging-types.js:339:5)
I20200515-00:22:30.229(3)?     at Object.validateMessage (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/messaging/messaging-types.js:49:5)
I20200515-00:22:30.230(3)?     at Messaging.send (/Users/roshdy/.meteor/packages/activitree_push/.2.0.4.18i3ti2.hq4j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/firebase-admin/lib/messaging/messaging.js:215:27)
I20200515-00:22:30.230(3)?     at sendNotification (packages/activitree:push/lib/server/notification.js:108:18)
I20200515-00:22:30.230(3)?     at self.sendNotification (packages/activitree:push/lib/server/pushToDevice.js:44:56)
I20200515-00:22:30.230(3)?     at packages/activitree:push/lib/server/pushToDevice.js:63:12
I20200515-00:22:30.230(3)?     at packages/mongo/mongo_driver.js:1116:25
I20200515-00:22:30.230(3)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
I20200515-00:22:30.230(3)?     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1115:10)
I20200515-00:22:30.230(3)?     at Cursor.<computed> [as map] (packages/mongo/mongo_driver.js:887:44)
I20200515-00:22:30.230(3)?     at querySend (packages/activitree:push/lib/server/pushToDevice.js:56:36)
I20200515-00:22:30.230(3)?     at self.serverSend (packages/activitree:push/lib/server/pushToDevice.js:170:14)
I20200515-00:22:30.230(3)?     at sendNotification (packages/activitree:push/lib/server/pushToDevice.js:195:29)
I20200515-00:22:30.230(3)?     at packages/activitree:push/lib/server/pushToDevice.js:237:13
I20200515-00:22:30.230(3)?     at packages/mongo/mongo_driver.js:1116:25
I20200515-00:22:30.230(3)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
I20200515-00:22:30.231(3)?     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1115:10)
I20200515-00:22:30.231(3)?     at Cursor.<computed> [as map] (packages/mongo/mongo_driver.js:887:44)
I20200515-00:22:30.231(3)?     at packages/activitree:push/lib/server/pushToDevice.js:235:30
I20200515-00:22:30.231(3)?     at packages/activitree:push/lib/server/pushToDevice.js:16:7
I20200515-00:22:30.231(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200515-00:22:30.231(3)?     at packages/meteor.js:550:25 {
I20200515-00:22:30.231(3)?   errorInfo: {
I20200515-00:22:30.231(3)?     code: 'messaging/invalid-payload',
I20200515-00:22:30.231(3)?     message: 'android.data must only contain string values'
I20200515-00:22:30.231(3)?   },
I20200515-00:22:30.231(3)?   codePrefix: 'messaging'
I20200515-00:22:30.231(3)? }
I20200515-00:22:30.231(3)? Push: Could not send notification id: "QdLrJEWHQtDDZMhHC", Error: android.data must only contain string values
```
